# Question 01

# Prerequisite the libraries
library("seqinr")
library("R.utils")
library("rBLAST")

# Download the E.coli Sequence from the Ensemble FTP page
download.file("ftp://ftp.ensemblgenomes.org/pub/bacteria/release-42/fasta/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655/cds/Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.cds.all.fa.gz",destfile = "e.coli.fa.gz")

# Decompress the file
gunzip("e.coli.fa.gz")

# Make the database
makeblastdb("e.coli.fa",dbtype="nucl","-parse_seqids")

# Question 02

# Download the sample file
download.file("https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part2_files/sample.fa", destfile = "sample.fa")

# Read it into R
s <-read.fasta("sample.fa")
mysequence <-s[[51]]
mysequence
str(mysequence)

# Calculate the GC content of the sequence
seqinr::GC (mysequence)

# Calculate the sequence Length
seqinr::getLength(mysequence)

# Question 3
download.file("https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part2_files/mutblast_functions.R", destfile = "mutblast.R")
source("mutblast.R")

# Test the function
res <- myblastn_tab(myseq = mysequence, db = "e.coli.fa")
res


# To determine the first 3 hits
hits <- as.character(res$sseqid[1:3])
hits
hits <- c(hits, "AAC77139")
hits
db <- read.fasta("e.coli.fa")
str(db[1:3])
head(names(db[1:3]))

# Question 04

# Finding mismatches for 50 substitutions
myecolimutator <- mutator(mysequence,50)
res <- myblastn_tab(myseq = myecolimutator, db = "e.coli.fa")
res

# Question 05

myecolimutator <- mutator(mysequence,100)
res <- myblastn_tab(myseq = myecolimutator, db = "e.coli.fa")
if (is.null(res)) {myres= 0} else {myres = 1}
myres

myecolimutator <- mutator(mysequence,150)
res <- myblastn_tab(myseq = myecolimutator, db = "e.coli.fa")
if (is.null(res)) {myres= 0} else {myres = 1}
myres

myecolimutator <- mutator(mysequence,200)
res <- myblastn_tab(myseq = myecolimutator, db = "e.coli.fa")
if (is.null(res)) {myres= 0} else {myres = 1}
myres

myecolimutator <- mutator(mysequence,250)
res <- myblastn_tab(myseq = myecolimutator, db = "e.coli.fa")
if (is.null(res)) {myres= 0} else {myres = 1}
myres

myfunc <- function(myseq,nmut) 
  mutseq <- mutator( myseq= mysequence, nmut = 222) 
  res <- myblastn_tab(myseq= mutseq, db= "e.coli.fa") 
  if (is.null(res)) {myres= 0} else {myres = 1}
  return(myres)

myfunc(myseq = allocated_Seq, nmut = 222) 
myfunc(myseq=seq,nmut=222)
replicate(n = 100, expr = myfunc(myseq=seq,nmut=10) )
n <- c(0,100,200,300)
myfunc_rep <- function(nmut){
finalres <- sapply( n, myfunc_rep )
finalres <- sapply(n,function( nmut ) {  mean(replicate(n = 100, expr = myfunc(myseq=seq,nmut=nmut) ) ) } )  



